services:
  localstack:
    # https://app.localstack.cloud/getting-started
    # https://app.localstack.cloud/inst/default/status
    # https://hub.docker.com/r/localstack/localstack
    # docker pull localstack/localstack:4.11.1
    # image: localstack/localstack:latest
    ## ---
    # How to see a particular service:
    # https://app.localstack.cloud/getting-started
    # https://app.localstack.cloud/inst/default/status
    # -----
    image: localstack/localstack:4.11.1
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,sqs,lambda
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}   # optional
      - LOCALSTACK_UI=1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "8083:8080"        # <-- Web UI exposed here! http://localhost:4566/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"
      - ./docker/volumes/localstack/init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./docker/volumes/localstack/data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
